Repository adaptui/react, pull requests merged in 2020-11, with the labels that each got.

#130 test: fixed tests
  src/calendar/__tests__/RangeCalendar.test.tsx
Labels: test 🧪

#126 test: added slider tests
  babel.config.js
  jest.config.ts
  package.json
  src/slider/__tests__/Slider.test.tsx
  src/slider/stories/Slider.stories.tsx
  src/utils/test-utils.ts
Labels: test 🧪

#129 chore: wip runtime ts transpile examples
  .gitignore
  .storybook/main.ts
  package.json
  scripts/generate-js.js
  scripts/transpile-ts.js
  src/accordion/stories/Accordion.stories.tsx
  src/accordion/stories/AccordionStyled.stories.tsx
  src/accordion/stories/templates.ts
  yarn.lock
Labels: documentation 📚, enhancements 📈

#133 test: added more test cases for slider
  src/slider/__tests__/Slider.test.tsx
Labels: test 🧪

#124 Number input v2
  src/accordion/__keys.ts
  src/accordion/stories/Accordion.component.tsx
  src/accordion/stories/AccordionStyled.component.tsx
  src/number-input/NumberInput.ts
  src/number-input/NumberInputDecrementButton.ts
  src/number-input/NumberInputIncrementButton.ts
  src/number-input/NumberInputState.ts
  src/number-input/__keys.ts
  src/number-input/__test__/NumberInput.test.tsx
  src/number-input/__test__/useSpinner.test.tsx
  src/number-input/__test__/utils.test.ts
  src/number-input/__utils.ts
  src/number-input/createNumberInputButtonsHook.ts
  src/number-input/helpers/index.ts
  src/number-input/helpers/useSpinner.ts
  src/number-input/stories/NumberInput.component.tsx
  src/number-input/stories/NumberInput.stories.tsx
  src/number-input/stories/templates.ts
Labels: component ⚙️, enhancements 📈

#135 test: added multi slider tests
  src/slider/SliderState.ts
  src/slider/__tests__/MultiSlider.test.tsx
Labels: test 🧪

#144 Pickers chore
  src/calendar/CalendarButton.ts
  src/calendar/CalendarCell.ts
  src/calendar/CalendarCellButton.ts
  src/calendar/CalendarGrid.ts
  src/calendar/CalendarHeader.ts
  src/calendar/CalendarState.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__keys.ts
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/__tests__/utils.test.tsx
  src/calendar/helpers/index.ts
  src/calendar/helpers/useWeekStart.ts
  src/calendar/stories/Calendar.component.tsx
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/RangeCalendar.component.tsx
  src/datepicker/DatePickerState.ts
  src/datepicker/DatePickerTrigger.ts
  src/datepicker/DateRangePickerState.ts
  src/datepicker/__keys.ts
  src/datepicker/helpers.ts
  src/datepicker/stories/DatePicker.component.tsx
  src/datepicker/stories/DatePicker.stories.tsx
  src/datepicker/stories/DateRangePicker.component.tsx
  src/picker-base/PickerBase.ts
  src/picker-base/PickerBaseContent.ts
  src/picker-base/PickerBaseState.ts
  src/picker-base/PickerBaseTrigger.ts
  src/picker-base/__keys.ts
  src/picker-base/stories/PickerBase.component.tsx
  src/picker-base/stories/PickerBase.stories.tsx
  src/segment/Segment.ts
  src/segment/SegmentState.ts
  src/segment/__tests__/Segment.test.tsx
  src/segment/__tests__/SegmentState.test.ts
  src/segment/__tests__/useSpinButton.test.tsx
  src/segment/__tests__/utils.test.ts
  src/segment/helpers/index.ts
  src/segment/helpers/useSpinButton.ts
  src/segment/stories/Segment.component.tsx
  src/segment/stories/Segment.stories.tsx
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerColumnValue.ts
  src/timepicker/TimePickerContent.ts
  src/timepicker/TimePickerState.ts
  src/timepicker/TimePickerTrigger.ts
  src/timepicker/__keys.ts
  src/timepicker/__tests__/utils.test.ts
  src/timepicker/helpers.ts
  src/toast/__keys.ts
Labels: enhancements 📈

#146 test: refactored all tests
  src/accordion/__tests__/Accordion.test.tsx
  src/accordion/__tests__/AccordionState.test.ts
  src/accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  src/accordion/__tests__/__snapshots__/AccordionState.test.ts.snap
  src/calendar/__tests__/Calendar.test.tsx
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/__tests__/__snapshots__/utils.test.tsx.snap
  src/calendar/__tests__/utils.test.tsx
  src/datepicker/__tests__/DatePicker.test.tsx
  src/datepicker/__tests__/DateRangePicker.test.tsx
  src/number-input/__test__/NumberInput.test.tsx
  src/picker-base/__tests__/BasePicker.test.tsx
  src/picker-base/__tests__/BasePicker.tests.tsx
  src/picker-base/__tests__/__snapshots__/BasePicker.test.tsx.snap
  src/progress/__tests__/Progress.test.tsx
  src/segment/__tests__/Segment.test.tsx
  src/segment/__tests__/SegmentState.test.ts
  src/segment/__tests__/__snapshots__/SegmentState.test.ts.snap
  src/segment/__tests__/utils.test.ts
  src/slider/__tests__/MultiSlider.test.tsx
  src/slider/__tests__/Slider.test.tsx
  src/timepicker/__tests__/TimePicker.test.tsx
  src/toast/ToastState.ts
  src/toast/__tests__/Toast.test.tsx
  src/toast/__tests__/ToastState.test.ts
  src/toast/__tests__/__snapshots__/ToastState.test.ts.snap
  src/utils/LiveAnnouncer.test.tsx
  src/utils/__snapshots__/LiveAnnouncer.test.tsx.snap
  src/utils/test-utils.ts
  src/utils/utils.test.tsx
Labels: test 🧪

#149 feat(story): ✨ isolate story styles with post css
  .storybook/postcss.config.js
  .storybook/preview.tsx
  .storybook/webpack.config.js
  package.json
  src/accordion/stories/AccordionBasic.component.tsx
  src/accordion/stories/AccordionBasic.stories.tsx
  src/calendar/stories/CalendarBase.component.tsx
  src/calendar/stories/CalendarBase.css
  src/calendar/stories/CalendarBase.stories.tsx
  src/calendar/stories/CalendarRange.component.tsx
  src/calendar/stories/CalendarRange.css
  src/calendar/stories/CalendarRange.stories.tsx
  src/datepicker/stories/DatePickerBase.component.tsx
  src/datepicker/stories/DatePickerBase.css
  src/datepicker/stories/DatePickerBase.stories.tsx
  src/datepicker/stories/DatePickerRange.component.tsx
  src/datepicker/stories/DatePickerRange.css
  src/datepicker/stories/DatePickerRange.stories.tsx
  src/number-input/stories/NumberInput.stories.tsx
  src/select/stories/Combobox.stories.tsx
  src/select/stories/Select.stories.tsx
  src/slider/stories/MultiSlider.stories.tsx
  src/slider/stories/RangeSlider.stories.tsx
  src/slider/stories/SingleOriginSlider.stories.tsx
  src/slider/stories/SingleReversedSlider.stories.tsx
  src/slider/stories/SingleSlider.stories.tsx
  src/slider/stories/SingleVerticalSlider.stories.tsx
  src/slider/stories/Slider.stories.tsx
  src/toast/stories/ToastBasic.component.tsx
  src/toast/stories/ToastBasic.css
  src/toast/stories/ToastBasic.stories.tsx
  src/toast/stories/ToastCSSAnimated.stories.tsx
  src/toast/stories/ToastReactSpring.stories.tsx
  yarn.lock
Labels: documentation 📚

#143 feat: accordion types improvements
  @types-tests/types.test-d.ts
  package.json
  src/accordion/AccordionPanel.ts
  src/accordion/AccordionState.ts
  src/accordion/AccordionTrigger.ts
  src/accordion/__keys.ts
  src/accordion/__tests__/Accordion.test.tsx
  src/accordion/__tests__/AccordionState.test.ts
  src/accordion/__tests__/__snapshots__/AccordionState.test.ts.snap
  src/accordion/index.ts
  src/accordion/stories/AccordionBasic.component.tsx
  src/accordion/stories/AccordionBasic.stories.tsx
  src/accordion/stories/AccordionStyled.stories.tsx
  src/accordion/types.ts
  yarn.lock
Labels: enhancements 📈

#159 fix(select): 🐛 focus the popover on loop from both ends
  src/select/Select.ts
  src/select/SelectListState.ts
  src/select/SelectPopoverState.ts
  src/select/__tests__/Select.test.tsx
  src/select/__tests__/__snapshots__/Select.test.tsx.snap
Labels: enhancements 📈

#165 refactor(role): ♻️ replace Box with Role from reakit
  src/breadcrumbs/Breadcrumbs.ts
  src/calendar/Calendar.ts
  src/calendar/CalendarCell.ts
  src/calendar/CalendarGrid.ts
  src/calendar/CalendarHeader.ts
  src/calendar/CalendarWeekTitle.ts
  src/meter/Meter.ts
  src/pagination/Pagination.ts
  src/picker-base/PickerBase.ts
  src/progress/Progress.ts
  src/slider/SliderThumb.ts
  src/slider/SliderTrack.ts
Labels: enhancements 📈
