Repository adaptui/react, pull requests merged in 2020-09, with the labels that each got.

#28 Pagination v1
  src/index.js
  src/meter/index.ts
  src/pagination/Pagination.ts
  src/pagination/PaginationButton.ts
  src/pagination/PaginationState.ts
  src/pagination/__keys.ts
  src/pagination/index.ts
  src/pagination/stories/Pagination.stories.tsx
  src/progress/index.ts
  src/select/index.ts
  src/toast/stories/AnimatedToast.stories.tsx
  src/toast/stories/BasicToast.stories.tsx
Labels: component ⚙️

#32 feat(meter): ✨ add meter functionalities
  src/meter/Meter.ts
  src/meter/MeterState.ts
  src/meter/__key.ts
  src/meter/__utils.ts
  src/meter/stories/LinearMeter.stories.tsx
  src/slider/SliderState.ts
  src/utils.tsx
Labels: feature 🚀

#33 test: added tests for link
  src/accordion/__tests__/Accordion.test.tsx
  src/link/__tests__/AriaLink.test.tsx
  src/link/__tests__/Link.test.tsx
  src/number-input/__test__/NumberInput.test.tsx
Labels: test 🧪

#36 test: added tests for breadcrumb
  src/breadcrumbs/__tests__/Breadcrumbs.test.tsx
Labels: test 🧪

#35 chore: added react hook form examples
  package.json
  src/number-input/stories/NumberInput.stories.tsx
  src/slider/stories/Slider.stories.tsx
Labels: documentation 📚

#34 refactor(imports): ♻️ organize imports on all components
  src/accordion/AccordionPanel.ts
  src/accordion/AccordionState.ts
  src/accordion/__tests__/AccordionState.test.ts
  src/button/AriaToggleButton.ts
  src/button/stories/AriaButton.stories.tsx
  src/button/stories/AriaToggleButton.stories.tsx
  src/button/stories/Buttons.tsx
  src/button/stories/ReakitButton.stories.tsx
  src/drawer/Drawer.ts
  src/drawer/DrawerCloseButton.ts
  src/drawer/__keys.ts
  src/drawer/stories/Drawer.stories.tsx
  src/index.ts
  src/interactions/stories/Interactions.stories.tsx
  src/number-input/__utils.ts
  src/number-input/stories/NumberInput.stories.tsx
  src/pagination/Pagination.ts
  src/pagination/PaginationButton.ts
  src/pagination/PaginationState.ts
  src/pagination/__keys.ts
  src/pagination/stories/Pagination.stories.tsx
  src/progress/__tests__/Progress.test.tsx
  src/select/Select.ts
  src/select/SelectInput.ts
  src/select/SelectMenu.ts
  src/select/SelectOption.ts
  src/select/SelectState.ts
  src/select/SelectTrigger.ts
  src/select/__utils.ts
  src/slider/SliderState.ts
  src/toast/ToastProvider.tsx
  src/toast/ToastState.ts
  src/toast/stories/BasicToast.stories.tsx
  src/utils/index.ts
  src/utils/storybook/index.tsx
Labels: enhancements 📈

#38 test: added tests for toast
  src/toast/ToastProvider.tsx
  src/toast/ToastState.ts
  src/toast/__tests__/Toast.test.tsx
  src/toast/__tests__/ToastState.test.ts
  src/toast/stories/Demo.tsx
Labels: test 🧪

#40 fix: toast ally issue
  src/toast/ToastController.tsx
  src/toast/stories/Demo.tsx
Labels: accessibility ♿️

#41 test: improved toast tests
  src/toast/__tests__/Toast.test.tsx
Labels: test 🧪

#39 add: meter tests & storybook examples with control support
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  package.json
  src/meter/Meter.ts
  src/meter/MeterState.ts
  src/meter/__examples__/__tests__/Meter.test.tsx
  src/meter/__examples__/__tests__/statehook-test-data.ts
  src/meter/__examples__/index.tsx
  src/meter/__examples__/stories/CircularMeter.stories.tsx
  src/meter/__examples__/stories/LinearMeter.stories.tsx
  src/meter/stories/LinearMeter.stories.tsx
  tsconfig.json
Labels: documentation 📚, test 🧪

#46 infra: added auto key generation script
  package.json
  scripts/build/keys.js
  scripts/utils.js
  src/accordion/__keys.ts
  src/breadcrumbs/BreadcrumbLink.ts
  src/breadcrumbs/__keys.ts
  src/button/__keys.ts
  src/link/Link.ts
  src/link/__keys.ts
  src/meter/Meter.ts
  src/meter/__key.ts
  src/meter/__keys.ts
  src/number-input/NumberInput.ts
  src/number-input/__keys.ts
  src/number-input/createNumberInputButtonsHook.ts
  src/pagination/__keys.ts
  src/progress/__keys.ts
  src/select/SelectInput.ts
  src/select/SelectMenu.ts
  src/select/SelectOption.ts
  src/select/SelectTrigger.ts
  src/select/__keys.ts
  src/slider/__keys.ts
  src/toast/__keys.ts
Labels: enhancements 📈, refactor ♻️

#47 feat(accordion): ✨ update accordion to expose panel open
  src/accordion/AccordionItem.ts
  src/accordion/AccordionItem.tsx
  src/accordion/AccordionPanel.ts
  src/accordion/AccordionState.ts
  src/accordion/AccordionTrigger.ts
  src/accordion/__keys.ts
  src/accordion/stories/Accordion.stories.tsx
  src/accordion/stories/index.css
Labels: refactor ♻️

#48 chore(deps): ⬆️ update multiple deps to latest
  package.json
Labels: refactor ♻️

#54 feat: added CalendarHeader component
  src/calendar-v1/Calendar.ts
  src/calendar-v1/CalendarButton.ts
  src/calendar-v1/CalendarCell.ts
  src/calendar-v1/CalendarCellButton.ts
  src/calendar-v1/CalendarGrid.ts
  src/calendar-v1/CalendarHeader.ts
  src/calendar-v1/CalendarState.ts
  src/calendar-v1/__keys.ts
  src/calendar-v1/index.ts
  src/calendar-v1/stories/Calendar.stories.tsx
Labels: enhancements 📈

#53 feat: return daysOfMonths to map easily
  src/calendar-v1/Calendar.ts
  src/calendar-v1/CalendarButton.ts
  src/calendar-v1/CalendarCell.ts
  src/calendar-v1/CalendarCellButton.ts
  src/calendar-v1/CalendarGrid.ts
  src/calendar-v1/CalendarHeader.ts
  src/calendar-v1/CalendarState.ts
  src/calendar-v1/__keys.ts
  src/calendar-v1/__utils.ts
  src/calendar-v1/stories/Calendar.stories.tsx
  src/calendar-v1/useWeekStart.ts
Labels: enhancements 📈

#51 feat(calendar): ✨ version 1
  package.json
  src/calendar-v1/Calendar.ts
  src/calendar-v1/CalendarButton.ts
  src/calendar-v1/CalendarCell.ts
  src/calendar-v1/CalendarCellButton.ts
  src/calendar-v1/CalendarGrid.ts
  src/calendar-v1/CalendarHeader.ts
  src/calendar-v1/CalendarState.ts
  src/calendar-v1/CalendarWeekTitle.ts
  src/calendar-v1/__keys.ts
  src/calendar-v1/__utils.ts
  src/calendar-v1/index.ts
  src/calendar-v1/stories/Calendar.stories.tsx
  src/calendar-v1/stories/index.css
  src/calendar-v1/useWeekStart.ts
  src/select/stories/style.css
Labels: component ⚙️, feature 🚀

#61 refactor(range-calendar): ♻️ review changes and fix bugs with space
  src/calendar-v1/CalendarCell.ts
  src/calendar-v1/CalendarCellButton.ts
  src/calendar-v1/CalendarGrid.ts
  src/calendar-v1/CalendarRangeState.ts
  src/calendar-v1/CalendarState.ts
  src/calendar-v1/RangeCalendar.ts
  src/calendar-v1/RangeCalendarState.ts
  src/calendar-v1/__keys.ts
  src/calendar-v1/__utils.ts
  src/calendar-v1/index.ts
  src/calendar-v1/stories/Calendar.stories.tsx
  src/calendar-v1/stories/RangeCalendar.stories.tsx
  src/calendar-v1/stories/index.css
  src/calendar-v1/stories/range-style.css
Labels: enhancements 📈

#57 feat: added range calendar
  package.json
  src/calendar-v1/CalendarCell.ts
  src/calendar-v1/__utils.ts
  src/calendar/Calendar.ts
  src/calendar/CalendarButton.ts
  src/calendar/CalendarCell.ts
  src/calendar/CalendarCellButton.ts
  src/calendar/CalendarGrid.ts
  src/calendar/CalendarHeader.ts
  src/calendar/CalendarState.ts
  src/calendar/CalendarWeekTitle.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__keys.ts
  src/calendar/__utils.ts
  src/calendar/index.d.ts
  src/calendar/index.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/calendar/stories/index.css
  src/calendar/stories/range-style.css
  src/calendar/useWeekStart.ts
  src/utils/LiveAnnouncer.tsx
Labels: feature 🚀

#60 chore(deps): ⬆️ update project & dev deps
  package.json
  src/breadcrumbs/__tests__/Breadcrumbs.test.tsx
  src/link/__tests__/Link.test.tsx
  src/slider/SliderState.ts
Labels: refactor ♻️
