Repository adaptui/react, pull requests merged in 2020-10, with the labels that each got.

#64 build(release): 👷 add a release pipeline with standard version
  .versionrc.json
  package.json
Labels: enhancements 📈

#69 fix: breadcrumb isCurrent disabled should be false
  src/breadcrumbs/BreadcrumbLink.ts
  src/breadcrumbs/__tests__/Breadcrumbs.test.tsx
Labels: accessibility ♿️, bug fix 🐛

#68 refactor: improved drawer types & fixed drawer bugs
  src/drawer/Drawer.ts
  src/drawer/DrawerCloseButton.ts
  src/drawer/__keys.ts
  src/drawer/stories/Drawer.stories.tsx
Labels: enhancements 📈

#70 Datepicker v3
  src/calendar/__utils.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/CalendarComponent.tsx
  src/calendar/stories/index.css
  src/datepicker/DatePicker.ts
  src/datepicker/DatePickerContent.ts
  src/datepicker/DatePickerFieldState.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DatePickerTrigger.ts
  src/datepicker/DateSegment.ts
  src/datepicker/DateSegmentField.ts
  src/datepicker/__keys.ts
  src/datepicker/__utils.ts
  src/datepicker/index.d.ts
  src/datepicker/index.ts
  src/datepicker/stories/DatePicker.stories.tsx
  src/datepicker/stories/index.css
Labels: enhancements 📈

#72 Datepicker stories
  src/datepicker/DatePicker.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DatePickerTrigger.ts
  src/datepicker/DateSegment.ts
  src/datepicker/stories/DatePicker.stories.tsx
  src/datepicker/stories/index.css
Labels: enhancements 📈

#76 test: added tests for segment
  package.json
  src/segment-spinner/__tests__/Segment.test.tsx
Labels: test 🧪

#80 refactor(time-picker): ♻️ new timepicker state with much lesser code
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerColumnValue.ts
  src/timepicker/TimePickerState.ts
  src/timepicker/__utils.ts
  src/timepicker/stories/TimePicker.stories.tsx
Labels: enhancements 📈, refactor ♻️

#79 test: added tests for SegmentState
  src/segment-spinner/__tests__/SegmentState.test.ts
Labels: test 🧪

#81 refactor(types): 🏷️ update types for date,time & calendar
  src/calendar/CalendarHeader.ts
  src/calendar/CalendarState.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__utils.ts
  src/calendar/index.d.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/CalendarComponent.tsx
  src/datepicker/DatePickerState.ts
  src/datepicker/__utils.ts
  src/datepicker/index.d.ts
  src/datepicker/stories/DatePicker.stories.tsx
  src/segment/SegmentState.ts
  src/segment/__utils.ts
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerState.ts
  src/utils/index.ts
  src/utils/types.ts
Labels: refactor ♻️

#75 Timepicker v2
  src/calendar/CalendarHeader.ts
  src/calendar/CalendarState.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__utils.ts
  src/calendar/index.d.ts
  src/calendar/index.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/CalendarComponent.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/datepicker/DatePicker.ts
  src/datepicker/DatePickerContent.ts
  src/datepicker/DatePickerSegment.ts
  src/datepicker/DatePickerSegmentField.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DatePickerTrigger.ts
  src/datepicker/DateSegment.ts
  src/datepicker/DateSegmentField.ts
  src/datepicker/__keys.ts
  src/datepicker/__utils.ts
  src/datepicker/index.d.ts
  src/datepicker/index.ts
  src/datepicker/stories/DatePicker.stories.tsx
  src/picker-base/PickerBase.ts
  src/picker-base/PickerBaseContent.ts
  src/picker-base/PickerBaseState.ts
  src/picker-base/PickerBaseTrigger.ts
  src/picker-base/__keys.ts
  src/picker-base/index.ts
  src/segment/Segment.ts
  src/segment/SegmentField.ts
  src/segment/SegmentState.ts
  src/segment/__keys.ts
  src/segment/__utils.ts
  src/segment/index.ts
  src/segment/stories/Segment.stories.tsx
  src/segment/stories/index.css
  src/timepicker/TimePicker.ts
  src/timepicker/TimePickerColumn.ts
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerColumnValue.ts
  src/timepicker/TimePickerContent.ts
  src/timepicker/TimePickerSegment.ts
  src/timepicker/TimePickerSegmentField.ts
  src/timepicker/TimePickerState.ts
  src/timepicker/TimePickerTrigger.ts
  src/timepicker/__keys.ts
  src/timepicker/__utils.ts
  src/timepicker/index.ts
  src/timepicker/stories/TimePicker.stories.tsx
  src/timepicker/stories/index.css
  src/utils/__keys.ts
  src/utils/index.ts
  src/utils/types.ts
Labels: enhancements 📈

#59 feat: added TimePicker v1
  src/calendar/CalendarHeader.ts
  src/calendar/CalendarState.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__tests__/Calendar.test.tsx
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/__utils.ts
  src/calendar/index.d.ts
  src/calendar/index.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/CalendarComponent.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/datepicker/DatePicker.ts
  src/datepicker/DatePickerContent.ts
  src/datepicker/DatePickerSegment.ts
  src/datepicker/DatePickerSegmentField.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DatePickerTrigger.ts
  src/datepicker/DateSegment.ts
  src/datepicker/DateSegmentField.ts
  src/datepicker/__keys.ts
  src/datepicker/__utils.ts
  src/datepicker/index.d.ts
  src/datepicker/index.ts
  src/datepicker/stories/DatePicker.stories.tsx
  src/picker-base/PickerBase.ts
  src/picker-base/PickerBaseContent.ts
  src/picker-base/PickerBaseState.ts
  src/picker-base/PickerBaseTrigger.ts
  src/picker-base/__keys.ts
  src/picker-base/index.ts
  src/segment/Segment.ts
  src/segment/SegmentField.ts
  src/segment/SegmentState.ts
  src/segment/__keys.ts
  src/segment/__tests__/Segment.test.tsx
  src/segment/__tests__/SegmentState.test.ts
  src/segment/__utils.ts
  src/segment/index.ts
  src/segment/stories/Segment.stories.tsx
  src/segment/stories/index.css
  src/timepicker/TimePicker.ts
  src/timepicker/TimePickerColumn.ts
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerColumnValue.ts
  src/timepicker/TimePickerContent.ts
  src/timepicker/TimePickerSegment.ts
  src/timepicker/TimePickerSegmentField.ts
  src/timepicker/TimePickerState.ts
  src/timepicker/TimePickerTrigger.ts
  src/timepicker/__keys.ts
  src/timepicker/__utils.ts
  src/timepicker/index.ts
  src/timepicker/stories/TimePicker.stories.tsx
  src/timepicker/stories/index.css
  src/utils/__keys.ts
  src/utils/index.ts
  src/utils/types.ts
Labels: feature 🚀

#83 test: added test for BasePicker
  src/picker-base/__tests__/BasePicker.tests.tsx
  src/picker-base/stories/BasePicker.stories.tsx
Labels: test 🧪

#84 fix: timepicker voiceover a11y
  src/timepicker/TimePickerColumn.ts
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerColumnValue.ts
  src/timepicker/TimePickerTrigger.ts
  src/timepicker/__keys.ts
Labels: accessibility ♿️, bug fix 🐛

#85 feat(time-picker): ✨ add keyboard navigation to the column
  src/timepicker/TimePickerColumn.ts
  src/timepicker/TimePickerContent.ts
Labels: enhancements 📈

#86 test: added test for timepicker
  src/timepicker/TimePickerColumn.ts
  src/timepicker/TimePickerColumnState.ts
  src/timepicker/TimePickerState.ts
  src/timepicker/__keys.ts
  src/timepicker/__tests__/TimePicker.test.tsx
Labels: test 🧪

#88 refactor(pickers): ♻️ improve state from dateValue to string
  src/calendar/CalendarCellButton.ts
  src/calendar/CalendarState.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__tests__/Calendar.test.tsx
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/__utils.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/datepicker/DatePickerContent.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DatePickerTrigger.ts
  src/datepicker/__utils.ts
  src/datepicker/stories/DatePicker.stories.tsx
  src/picker-base/__tests__/BasePicker.tests.tsx
  src/segment/SegmentField.ts
  src/segment/__utils.ts
  src/segment/stories/Segment.stories.tsx
  src/timepicker/TimePickerColumn.ts
  src/timepicker/TimePickerColumnValue.ts
  src/timepicker/TimePickerSegment.ts
  src/timepicker/TimePickerSegmentField.ts
  src/timepicker/TimePickerState.ts
  src/timepicker/TimePickerTrigger.ts
  src/timepicker/__tests__/TimePicker.test.tsx
  src/timepicker/__utils.ts
  src/timepicker/stories/TimePicker.stories.tsx
  src/utils/date.ts
  src/utils/index.ts
  src/utils/types.ts
  src/utils/useSpinButton.ts
Labels: enhancements 📈

#91 feat: added DateRangePicker
  src/calendar/__utils.ts
  src/calendar/stories/CalendarComponent.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/calendar/stories/svg-icons.tsx
  src/datepicker/DatePickerSegment.ts
  src/datepicker/DatePickerSegmentField.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DateRangePickerState.ts
  src/datepicker/__keys.ts
  src/datepicker/stories/DateRangePicker.stories.tsx
Labels: component ⚙️, feature 🚀

#90 Improved Accordion
  src/accordion/Accordion.ts
  src/accordion/AccordionItem.tsx
  src/accordion/AccordionPanel.ts
  src/accordion/AccordionState.ts
  src/accordion/AccordionTrigger.ts
  src/accordion/__keys.ts
  src/accordion/__tests__/Accordion.test.tsx
  src/accordion/__tests__/AccordionState.test.ts
  src/accordion/index.ts
  src/accordion/stories/Accordion.stories.tsx
  src/accordion/stories/index.css
  src/calendar/CalendarState.ts
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/datepicker/stories/DateRangePicker.stories.tsx
  src/number-input/stories/NumberInput.stories.tsx
  src/select/SelectState.ts
Labels: enhancements 📈, refactor ♻️

#92 refactor(aria): ♻️ remove aria dependencies with button & interactions
  package.json
  src/breadcrumbs/__tests__/Breadcrumbs.test.tsx
  src/button/AriaButton.ts
  src/button/AriaToggleButton.ts
  src/button/__keys.ts
  src/button/index.ts
  src/button/stories/AriaButton.stories.tsx
  src/button/stories/AriaToggleButton.stories.tsx
  src/button/stories/Buttons.tsx
  src/button/stories/ReakitButton.stories.tsx
  src/index.ts
  src/interactions/Focus.ts
  src/interactions/FocusRing.ts
  src/interactions/FocusVisible.ts
  src/interactions/FocusWithin.ts
  src/interactions/Focusable.ts
  src/interactions/Hover.ts
  src/interactions/Keyboard.ts
  src/interactions/Press.ts
  src/interactions/__keys.ts
  src/interactions/index.ts
  src/interactions/stories/Interactions.stories.tsx
  src/link/AriaLink.ts
  src/link/__keys.ts
  src/link/__tests__/AriaLink.test.tsx
  src/link/__tests__/Link.test.tsx
  src/link/index.ts
  src/link/stories/AriaLink.stories.tsx
  src/link/stories/Link.stories.tsx
  src/segment/SegmentState.ts
  src/slider/stories/Slider.stories.tsx
  src/utils/LiveAnnouncer.tsx
Labels: refactor ♻️

#93 test: fix range calendar broken tests for today
  src/calendar/__tests__/RangeCalendar.test.tsx
Labels: test 🧪

#96 refactor(storybook): ♻️ easier access to stories - removing sub folders
  src/accordion/stories/Accordion.stories.tsx
  src/breadcrumbs/stories/Breadcrumbs.stories.tsx
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/datepicker/stories/DatePicker.stories.tsx
  src/datepicker/stories/DateRangePicker.stories.tsx
  src/drawer/stories/Drawer.stories.tsx
  src/link/stories/Link.stories.tsx
  src/meter/__examples__/stories/CircularMeter.stories.tsx
  src/meter/__examples__/stories/LinearMeter.stories.tsx
  src/number-input/stories/NumberInput.stories.tsx
  src/pagination/stories/Pagination.stories.tsx
  src/picker-base/stories/BasePicker.stories.tsx
  src/progress/stories/CircularProgress.stories.tsx
  src/progress/stories/LinearProgress.stories.tsx
  src/segment/stories/Segment.stories.tsx
  src/select/stories/Combobox.stories.tsx
  src/select/stories/Select.stories.tsx
  src/slider/stories/Slider.stories.tsx
  src/timepicker/stories/TimePicker.stories.tsx
  src/toast/stories/AnimatedToast.stories.tsx
  src/toast/stories/BasicToast.stories.tsx
Labels: enhancements 📈

#95 Bundler check
  CHANGELOG.md
  babel-config.js
  package.json
  rollup.config.js
  src/calendar/__utils.ts
Labels: enhancements 📈

#97 refactor(reakit): ♻️ remove external deps in 3 components
  src/accordion/AccordionTrigger.ts
  src/accordion/__tests__/Accordion.test.tsx
  src/accordion/__tests__/AccordionState.test.ts
  src/accordion/__tests__/__snapshots__/Accordion.test.tsx.snap
  src/breadcrumbs/BreadcrumbLink.ts
  src/breadcrumbs/__tests__/Breadcrumbs.test.tsx
  src/breadcrumbs/__tests__/__snapshots__/Breadcrumbs.test.tsx.snap
  src/calendar/CalendarCell.ts
  src/calendar/CalendarCellButton.ts
  src/calendar/CalendarGrid.ts
  src/datepicker/DatePicker.ts
  src/link/Link.ts
  src/link/__tests__/Link.test.tsx
  src/number-input/__utils.ts
  src/picker-base/PickerBase.ts
  src/slider/Slider.ts
  src/slider/SliderThumb.ts
  src/slider/SliderTrack.ts
  src/utils/index.ts
  src/utils/types.ts
  tsconfig.json
Labels: enhancements 📈

#98 test: added datepicker tests
  src/datepicker/__tests__/DatePicker.test.tsx
Labels: test 🧪

#101 test: added tests for date range picker
  jest.config.js
  src/datepicker/DateRangePickerState.ts
  src/datepicker/__tests__/DateRangePicker.test.tsx
Labels: test 🧪

#102 test: improve tests & test coverage
  src/calendar/__tests__/Calendar.test.tsx
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/datepicker/__tests__/DateRangePicker.test.tsx
  src/number-input/__test__/NumberInput.test.tsx
  src/segment/__tests__/Segment.test.tsx
  src/utils/test-utils.ts
Labels: test 🧪

#105 fix(a11y): date range picker voiceover fix
  .github/workflows/test.yml
  package.json
  src/calendar/CalendarCellButton.ts
  src/calendar/CalendarState.ts
  src/calendar/RangeCalendarState.ts
  src/calendar/__keys.ts
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/datepicker/DatePickerSegment.ts
  src/datepicker/DatePickerState.ts
  src/datepicker/DateRangePickerState.ts
  src/datepicker/__keys.ts
  src/datepicker/__tests__/DateRangePicker.test.tsx
  src/datepicker/stories/DateRangePicker.stories.tsx
  src/meter/__keys.ts
  src/segment/Segment.ts
Labels: accessibility ♿️

#103 Progress improvement
  src/accordion/AccordionState.ts
  src/accordion/AccordionTrigger.ts
  src/accordion/stories/Accordion.stories.tsx
  src/accordion/stories/AccordionComponent.tsx
  src/meter/Meter.ts
  src/meter/MeterState.ts
  src/meter/__keys.ts
  src/meter/__tests__/Meter.test.tsx
  src/meter/stories/Meter.stories.tsx
  src/meter/stories/MeterComponent.tsx
  src/progress/Progress.ts
  src/progress/ProgressState.ts
  src/progress/__keys.ts
  src/progress/__tests__/Progress.test.tsx
  src/progress/stories/CircularProgress.stories.tsx
  src/progress/stories/CircularProgress.tsx
  src/progress/stories/LinearProgress.stories.tsx
  src/progress/stories/LinearProgress.tsx
  src/progress/stories/storybook-progress-utils.tsx
  src/utils/index.ts
Labels: enhancements 📈

#106 chore: datepicker & calendar storybook controls
  .storybook/preview.ts
  src/calendar/stories/Calendar.stories.tsx
  src/calendar/stories/RangeCalendar.stories.tsx
  src/calendar/stories/RangeCalendarComponent.tsx
  src/datepicker/stories/DatePicker.stories.tsx
  src/datepicker/stories/DatePickerComponent.tsx
  src/datepicker/stories/DateRangePicker.stories.tsx
  src/datepicker/stories/DateRangePickerComponent.tsx
Labels: documentation 📚, enhancements 📈

#109 test: added tests for live announcer
  src/utils/LiveAnnouncer.test.tsx
  src/utils/LiveAnnouncer.tsx
Labels: test 🧪

#110 test: added tests for useSpinButton
  src/utils/useSpinButton.test.tsx
  src/utils/useSpinButton.ts
Labels: test 🧪

#111 test: improve meter and range calendar tests
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/meter/MeterState.ts
  src/meter/__tests__/Meter.test.tsx
  src/meter/helpers.ts
Labels: test 🧪

#107 Progress & Meter State changes
  src/accordion/AccordionState.ts
  src/meter/MeterState.ts
  src/meter/__tests__/Meter.test.tsx
  src/meter/__tests__/helpers.test.ts
  src/meter/helpers.ts
  src/meter/stories/MeterComponent.tsx
  src/progress/Progress.ts
  src/progress/ProgressState.ts
  src/progress/__tests__/Progress.test.tsx
  src/progress/stories/CircularProgress.stories.tsx
  src/progress/stories/CircularProgress.tsx
  src/progress/stories/LinearProgress.stories.tsx
  src/progress/stories/LinearProgress.tsx
  src/utils/index.ts
  src/utils/utils.test.ts
Labels: enhancements 📈

#115 test: added tests for createContext
  src/utils/utils.test.tsx
Labels: test 🧪

#117 test: refactored all tests
  src/calendar/__tests__/Calendar.test.tsx
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/datepicker/__tests__/DatePicker.test.tsx
  src/datepicker/__tests__/DateRangePicker.test.tsx
  src/number-input/__test__/NumberInput.test.tsx
  src/pagination/__tests__/Pagination.test.tsx
  src/picker-base/__tests__/BasePicker.tests.tsx
  src/segment/__tests__/Segment.test.tsx
  src/slider/__tests__/Slider.test.tsx
  src/timepicker/__tests__/TimePicker.test.tsx
  src/utils/test-utils.ts
Labels: test 🧪

#118 test: added unit test for segment utils
  src/segment/__tests__/utils.test.ts
Labels: test 🧪

#112 Multi Slider
  src/accordion/AccordionPanel.ts
  src/accordion/AccordionState.ts
  src/slider/Slider.ts
  src/slider/SliderFilledTrack.ts
  src/slider/SliderInput.ts
  src/slider/SliderState.ts
  src/slider/SliderThumb.ts
  src/slider/SliderTrack.ts
  src/slider/__keys.ts
  src/slider/__tests__/Slider.test.tsx
  src/slider/__utils.ts
  src/slider/helpers/index.ts
  src/slider/helpers/textSelection.ts
  src/slider/helpers/useGlobalListeners.ts
  src/slider/helpers/useMove.ts
  src/slider/index.ts
  src/slider/stories/Slider.stories.tsx
  src/slider/stories/index.css
  src/slider/stories/styles.ts
Labels: feature 🚀

#121 test: added more test cases for calendar
  src/calendar/__tests__/Calendar.test.tsx
  src/calendar/__tests__/RangeCalendar.test.tsx
  src/calendar/stories/Calendar.stories.tsx
Labels: test 🧪

#128 test: fixed broken tests for today
  src/calendar/__tests__/Calendar.test.tsx
Labels: test 🧪
